require "./lib/fantasy_football_lookup/version"
require "./lib/fantasy_football_lookup/cli"
require "./lib/fantasy_football_lookup/team"
require "./lib/fantasy_football_lookup/player"
require "./lib/fantasy_football_lookup/scraper"
